spring:
  application:
    name: collab-editor
  datasource:
    # Use the DB_URL env var, or fallback to localhost for local machine dev
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/postgres}
    username: ${SPRING_DATASOURCE_USERNAME:scott}
    password: ${SPRING_DATASOURCE_PASSWORD:tiger}
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  data:
    redis:
      host: redis
      port: 6379
      timeout: 2000ms

jwt:
  access-token-expiration-ms: 900000       # 15 minutes
  refresh-token-expiration-ms: 604800000   # 7 days
  # Do not provide a default fallback for production cryptographic keys
  private-key: ${JWT_PRIVATE_KEY}
  public-key: ${JWT_PUBLIC_KEY}