spring:
  application:
    name: collab-editor
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    password: tiger
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
jwt:
    access-token-expiration-ms: 900000       # 15 minutes
    refresh-token-expiration-ms: 604800000   # 7 days
    secret: idkwhybutthisneedstobelongnahidekwhattofilladdingsomemoreforgoodmeasure